obj-m := wireview_hwmon.o
# The deb/rpm/AUR packaging substitutes the version placeholder below when
# it installs this file as /usr/src/wireview-hwmon-<ver>/Makefile.
ccflags-y += -DWIREVIEW_PKG_VERSION=\"@VERSION@\"
